changelog:
  categories:
    - title: Features
      labels: [feat, enhancement]
    - title: Fixes
      labels: [fix, bug]
    - title: Documentation
      labels: [docs]
    - title: Other changes
      labels: ["*"]
